spring:
  application:
    name: store-service

  config:
    import: optional:file:.env[.properties]

  datasource:
    master:
      hikari:
        jdbc-url: ${DB_MASTER_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
        maximum-pool-size: 5
        minimum-idle: 2
        connection-timeout: 30000   # 30초
        max-lifetime: 1800000       # 30분
        leak-detection-threshold: 60000  # 누수 감지
    slave:
      hikari:
        jdbc-url: ${DB_SLAVE_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
        maximum-pool-size: 5
        minimum-idle: 2
        connection-timeout: 30000   # 30초
        max-lifetime: 1800000       # 30분
        leak-detection-threshold: 60000  # 누수 감지

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: false
        highlight_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    url: ${DB_MASTER_URL}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    baseline-on-migrate: true
    baseline-version: 1
    validate-on-migrate: true
    clean-disabled: true

  data:
    elasticsearch:
      uris: ${ELASTICSEARCH_URI}

jwt:
  secret:
    key: ${JWT_SECRET_KEY}
    white-list:
      - /actuator/health
      - /actuator/prometheus
      - /error
      - /swagger-ui/**
      - /swagger-ui.html
      - /v3/api-docs/**
      - /v3/api-docs.yaml
      - /v3/api-docs.json
      - /api-docs/**
      - /swagger-resources/**
      - /webjars/**
      - /docs/**

logging:
  level:
    root: INFO
    com.couponpop.storeservice: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: INFO

  file:
    name: logs/application.log

  logback:
    rollingpolicy:
      file-name-pattern: logs/application-%d{yyyy-MM-dd}.%i.log
      max-file-size: 10MB
      max-history: 30