server:
  port: 8082

management:
  endpoints.web.exposure.include: health,info,prometheus
  endpoint.health.show-details: always

# client:
#   coupon-service:
#     name: coupon-service
#     url: http://localhost:8083